#!/bin/bash

cat jquery-1.7.2.js jquery.mousewheel.js jquery.localscroll-1.2.7-min.js jquery.scrollTo-1.4.2-min.js jquery.scrollorama.js mailHider.js jquery.jscrollpane.min.js main.js | uglifyjs -o javascript.js
